# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de633923748649b36fe00c4883484847dfbccc39106df1cca4a7972887c6d7a0dcec962bf705b46353bf0922d53d7d68b22c5538f3c63c1ffbc4f5eae88323e

test:
  secret_key_base: 5043d3e63201f1d353b2d757627f2146d3731b6ea2522e165982bdb89e9c980a64ba91595ab8074337ca2793641cd2a8ebedc7e3f248bf39671d0ed6b4eaa664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
